skeleton_one
Sllambias/yucca pull request #181
Opened 2024-08-05 13:01 UTC by juliamachnio

Skeleton first part

2024-09-17 09:09 UTC, Sllambias requested changes
minor changes needed :)

2024-09-17 09:09 UTC, Sllambias commented on yucca/modules/lightning_modules/YuccaLightningModule.py
Need to figure out a way so that the default lightning module doesn't always expect to find a skeleton

2024-09-17 09:09 UTC, Sllambias commented on yucca/pipeline/managers/alternative_managers/YuccaManager_Julia.py
Need a more appropriate name for the final version of this ;)

2024-09-23 09:14 UTC, Sllambias reviewed
Very nice, just a few minor comments to do final polish :)

2024-09-23 09:14 UTC, Sllambias commented on yucca/modules/data/augmentation/YuccaAugmentationComposer.py
can we move the skeleton transform to the end with the other label transforms? 
It's a bit awkwardly in the middle of the non-label transforms here :)

2024-09-23 09:14 UTC, Sllambias commented on yucca/modules/data/augmentation/YuccaAugmentationComposer.py
> +                # ),
should this be removed or made into a real transform for the validation?

2024-09-23 09:14 UTC, Sllambias commented on yucca/modules/data/augmentation/transforms/Skeleton.py
> +        # self.skip_label = skip_label
commented out arg, remove or implement?

2024-09-23 09:14 UTC, Sllambias approved these changes

2024-09-23 09:15 UTC, Sllambias commented
Very few comments, apart from that LGTM :)

2024-09-23 09:19 UTC, juliamachnio commented on yucca/modules/data/augmentation/YuccaAugmentationComposer.py
yes, we can

2024-09-23 09:20 UTC, juliamachnio commented on yucca/modules/data/augmentation/transforms/Skeleton.py
> +        # self.skip_label = skip_label
removed, old version

2024-09-23 09:48 UTC, Sllambias approved these changes
Just 1 change but feel free to merge after changing it, dont need to request review again - it's approved! 
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExa3lmNWZmbXc4NDBzaXNucXhzcG53bXBtd2RsbmNvZzk5emIwYmZ5ZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Od0QRnzwRBYmDU3eEO/giphy.gif)

2024-09-23 10:02 UTC, merged